### ISSUE TITLE
C64 PETSCII character set support

### ISSUE THREAD

**Issue by KeithHenrickson** [llvm-mos/llvm-mos-sdk#116]
It seems the only way to make the C64 work with strings is to type them in "ALL CAPS", because that's the set that lines up between ASCII/UTF8 and PETSCII.

The "right way" is to have a string decoration indicating that the programmer would like upper and lower case flipped.

**Comment by asiekierka** [comment]
I believe the best way to approach this would be to add `PETSCII` as a `-fexec-charset` option, however that is not currently supported by Clang. There's [an upstream PR](https://reviews.llvm.org/D93031) in development from IBM which would add this, after which (especially given [an RFC](https://discourse.llvm.org/t/rfc-adding-a-charset-converter-to-the-llvm-support-library/69795) to add dedicated character set conversion functionality to llvm/Support) it should be easy to add the necessary code to mark string literals as PETSCII.

**Comment by asiekierka** [comment]
Defining a simple textual character-set definition file format would also be a welcome feature for console developers, where it's not uncommon to desire a non-ASCII text formatting. I agree - combining the `-fexec-charset` patches with the ability to load a custom character set definition file sounds like a good idea.

**Comment by mysterymath** [comment]
This is now supported via C++20 character literals. It's not perfect, since it doesn't work in C, but the semantics are otherwise excellent, and it's the best we're likely to get in the near term future. A lot of chaff came up about `-fexec-charset`; it's very difficult to support generally if it differs across compilation units, since strings can end up in type names in C++, which can produce ODR violations. So for C++ the user defined literal approach seems just better, and for C, I'm inclined to wait for -fexec-charset upstream. Accordingly, closing this issue.
