### ISSUE TITLE
add_platform_object_file linking does not support custom opcodes

### ISSUE THREAD

**Issue by asiekierka** [llvm-mos/llvm-mos-sdk#118]
Trying to emit a `crt0.c` for a platform where it requires subtarget-specific opcodes (for example, RPC8/e MMU configuration, or PC Engine/HuC6280 MMU/CPU speed configuration) emits errors as follows:

```
cd /home/asie/Homebrew/MOS/llvm-mos-sdk/build/mos-platform/build/mos-platform/rpc8e && /home/asie/Homebrew/MOS/llvm-mos-sdk/build/_deps/llvm-mos-src/bin/ld.lld -r -o crt0.o --whole-archive /home/asie/Homebrew/MOS/llvm-mos-sdk/build/mos-platform/build/mos-platform/rpc8e/librpc8e-crt0-o.a
# [...]
error: instruction requires a CPU feature not currently enabled
  mmu #$02
  ^
# [...]
ld.lld: error: ld-temp.o <inline asm>:11:3: instruction requires a CPU feature not currently enabled
  mmu #$02
  ^
```

A functional workaround for this is adding `-mllvm -mcpu=mos65el02` to `add_platform_object_file` (or cloning its functionality in the platform's own CMakeLists), but I'm not sure how to add a clean, reusable approach with my CMake knowledge thus far.

Note that in such a situation, it does still emit the first error, but compilation succeeds - maybe the correct solution is adding subtarget information to the triple in LLVM bitcode files?

**Comment by mysterymath** [comment]
I'm a little confused about the issue here; is this blocking the RPC8 pull request? It looks like that uses -mcpu as an argument to the corresponding builds, which is what I'd expect. The compiler driver should already forward `-mcpu` flags to the compiler and assembler as needed, and all this information should already be stamped into the bitcode for each function in LTO by the time it reaches the linker.

**Comment by asiekierka** [comment]
It's not an issue anymore; sorry.
