### ISSUE TITLE
Modified Action53 reset.s doesn't get picked by build system

### ISSUE THREAD

**Issue by mysterymath** [llvm-mos/llvm-mos-sdk#182]
@jroweboy reported that their local changes to `reset.s` in their Action53 target didn't automatically get picked up by the build system, which took considerable time to debug. We should try to repro this, since it may point to a general issue in the dependency tracking of our CMake multi-build. This may be the same issue as #81; reporting separately pending further investigation.

**Comment by mysterymath** [comment]
@jroweboy, I wasn't able to reproduce this on my end. After a successful build, I replaced the contents of `reset.s` in the Action53 target with a syntax error, and re-running Ninja immediately produced an error. This was on Arch Linux x86-64. Are you still able to reproduce this on your end?

**Comment by jroweboy** [comment]
I think the issue is actually in the install step. I've been developing my game with an local copy of llvm-mos-sdk and i run the `ninja install` target after making changes to copy them to the local `llvm-mos/build` develop folder. It seems that during this step it detects the compiled reset.o file is `Up-to-date: /path/to/llvm-mos/build` and then doesn't copy it over.
