### ISSUE TITLE
Sanitize license compliance for dependent projects

### ISSUE THREAD

**Issue by johnwbyrd** [llvm-mos/llvm-mos-sdk#318]
The llvm-mos-sdk project has gone with an LLVM-compatible license, which is the Apache License v2.0 with LLVM Exceptions.  However, the llvm-mos-sdk project has come to incorporate code from a few other projects, such as PDCLib and cc65.  Each of these subprojects has its own license agreement, either public domain or BSD, with its own restrictions and covenants.

When incorporating code from various sources to make a new product, it is common to present those licenses from subprojects, in a way where the consumer can easily read and understand it, in order to decide whether they're willing to abide by those licenses.  There are several ways for doing this that I am aware of.

One way is to do manual collection and generation of a master COPYING file, which displays all the licenses for each of the subprojects.  Since this method is done manually, it is generally free form, and responsibility for keeping it correct falls on us.  This method seems fine for small projects.

One way is to follow the Debian standard, demonstrated [here](https://github.com/picolibc/picolibc/blob/main/COPYING.picolibc) for example.  This file is generated with a shell script that greps through each of the subprojects, looking for copyright information and appending discovered info to this generated list.

One way is to follow the [Yocto](https://www.yoctoproject.org/) standard, as I do at ${DAYJOB}, which includes licenses from thousands of subprojects.  The license file is generated in the SPDX format as an SBOM.  There are [multiple tools](https://blog.sonatype.com/5-tools-to-automate-sbom-creation) for generating an SBOM.  This may be overkill for such a small project, but such a solution scales to an arbitrary number of dependencies.

**Comment by mysterymath** [comment]
> The llvm-mos-sdk project has gone with an LLVM-compatible license, which is the Apache License v2.0 with LLVM Exceptions. However, the llvm-mos-sdk project has come to incorporate code from a few other projects, such as PDCLib and cc65. Each of these subprojects has its own license agreement, either public domain or BSD, with its own restrictions and covenants.

We shouldn't be shipping any BSD code to users in our binary SDK releases. We do compile code against BSD headers, but those headers contain only API definitions. Law definitely varies on this, but if that's a legal fiction we can't tolerate, then I'd consider it grounds for removal of that code from the SDK.

Public domain (or equivalent) code can be freely relicensed; accordingly, all public domain code in the SDK has been relicensed to Apache 2 w/ LLVM exceptions. So it's not really a separate concern from other contributions to the SDK.

We'll be stuck with zlib licensed code in the long term, due to our heavy cc65 dependency, but that's mostly fine; it's terms are very aggreeable.

The presence of MIT licensed code is a wart, and it's now limited to the NES target. Much of that code is probably better living out side of the SDK in the long term.

Accordingly, I think in the long run we really want to only have a couple licenses in the shipped SDK: ideally just zlib (cc65) and Apache 2 w/ LLVM. So a simple COPYING file should suffice; if it doesn't, then we and our users have bigger problems.

> One way is to do manual collection and generation of a master COPYING file, which displays all the licenses for each of the subprojects. Since this method is done manually, it is generally free form, and responsibility for keeping it correct falls on us. This method seems fine for small projects.

I've generally attempted to include the necessary licenses in our COPYING file, but I think you're right, it would be a good idea to

**Comment by mysterymath** [comment]
I'd really like to avoid the license soup that newlib and picolibc have ended up in; we should avoid building tooling intended to handle a vast array of licenses, because we shouldn't have a vast array of licenses in the SDK.

I had only placed licenses in the COPYING file that had requirements to do so, but I think you're right that it's a good idea to let users know which licenses they'll be bound by when they use which licenses and features, even if the terms are extremely light. I'll go through and add the remainder and a callout to where they're used.
