### ISSUE TITLE
Source code in assembly output

### ISSUE THREAD

**Issue by AGPX** [llvm-mos/llvm-mos-sdk#34]
Hi,

first of all, many many compliments! You've done a great job!
I have a question: I've tried the "-Wl,--lto-emit-asm" option, but I wish to understand if there's an option to interleave the assembly code with the source (as comment). This would be really useful to understand how a certain piece of code is translated. Is there a similar option?

Thanks in advance and keep the absolutely outstanding work!

**Comment by mysterymath** [comment]
Hey, thanks for the compliment!

IIRC this is a surprisingly old request in the larger Clang community; https://bugs.llvm.org/show_bug.cgi?id=16647 and https://bugs.llvm.org/show_bug.cgi?id=17465 are upstream issues that I know of. It looks like someone started work along those lines, but it stalled out.

It's not clear to me how difficult of an ask this is, but it's something that would definitely be better done upstream, rather than in LLVM-MOS. You might take a look at https://github.com/llvm/llvm-project/issues/17839; this is the Github ported version of the latter of the above bugs, and it looks like there's been some recent chatter about this.
