### ISSUE TITLE
Port Mesen testrunner to use libretro and EmuTest

### ISSUE THREAD

**Issue by mysterymath** [llvm-mos/llvm-mos-sdk#78]
It was a lot of work getting the Mesen testrunner to operate headlessly in CI. This won't scale to other emulators; Mesen was sort-of designed to be used as a test runner, but the others largely aren't, and they lack good scripting interfaces.

At least that used to be true, but the libretro project provides a cross-emulator control API, not for the purposes of test running, but so the same frontend can control vastly different emulators. It looks like the [emutest](https://github.com/kivutar/emutest) project is a libretro project that allows libretro emulator plugins to be driven headlessly in response to Lua scripts. The stated purpose is to test libretro plugins, but we can use it just as well to test our SDK. Assuming it works as well as it claims.

**Comment by mysterymath** [comment]
After a brief bit of exploration, I couldn't actually get the emutest or noarch frontends to work with any copy of the mesen libretro core I could find (I tried the Arch one and the one downloaded by my local RetroArch install).

**Comment by sehugg** [comment]
I managed to run the Nestopia (installed via apt) QuickNES, and Stella libretro cores on Ubuntu. Do you think those will work?

The drawback is that the best/only way to determine success or failure is to hash the framebuffer with get_fb_crc(), there doesn't seem to be a way to get RAM or CPU state. But it does screenshots and prints logs, so that might be enough, if the console can report its own result. And I don't think it'd be hard to extend emutest for missing features like audio and grabbing RAM (should the core support it)

**Comment by asiekierka** [comment]
RetroAchievements is based around grabbing RAM, so maybe something in that direction?

**Comment by sehugg** [comment]
I've gotten emutest working with the Stella2014 core, and Atari 2600 tests have found a couple of bugs already. It looks for an 8-byte pass/fail signature in RAM. I'll add a few more tests and do a PR, it's useful enough already.

Most of the NES tests work with the Nestopia core, but there are a few failures I haven't fully sussed. I think at least one is due to differences of opinion of which mappers canonically support which features. I've put it on a separate branch, but since you have Mesen working I don't think there's a rush to switch.

I think VICE, Atari800, and Beetle PCE could be future test targets that use this.

**Comment by mysterymath** [comment]
Closed by #241
