### ISSUE TITLE
Unexpected behavior of CBM KERNAL functions

### ISSUE THREAD

**Issue by mlund** [llvm-mos/llvm-mos-sdk#99]
For the snippet below, I get different behavior with cc65 and clang using the VICE emulator. I suspect it might be the calling conventions for the `mos-platform/commodore/*.s` functions (`setnam`, `setlfs`, `chkin`). Merely calling `chkin` causes the screen to scroll on clang. The very useful [cbm functions](https://www.pagetable.com/c64ref/kernal/) were introduced in #86 and #87. Ping @cnelson20.

~~~ C
// cl65 cbm_open.c -o open-cc65.prg --target c64
// mos-c64-clang cbm_open.c -o open-clang.prg
#include <cbm.h>
#include <stdio.h>

const char* filename = "SOMEFILE";

int main() {
    unsigned char s1, s2;
    unsigned char lfn = 8;
    unsigned char device = 8;
    unsigned char secondary_addr = 0;

    cbm_k_setlfs(lfn, device, secondary_addr);
    cbm_k_setnam(filename);

    s1 = cbm_k_open(); // Expected = 0; Clang = 199
    //s2 = cbm_k_chkin(lfn); // Expected = 0; on clang this causes the screen to scroll
    printf("open status = %d\n", s1);
    return 0;
}
~~~

**Comment by mlund** [comment]
For [`setlfs`](https://www.pagetable.com/c64ref/kernal/#SETLFS):
- setlfs reference:
  - A = lfn
  - X = device
  - Y = command (secondary address)
- Wiki: _The bytes composing numeric arguments are passed individually in A, then X, then RC2 to RC15._
- So `.s` looks good to me (`ldy __rc2`).

For [`setnam`](https://www.pagetable.com/c64ref/kernal/#SETNAM):
- setnam reference:
  - A = length of filename
  - X = low order address
  - Y = high order address
- Wiki: _Pointers are passed through RS1 through RS7_
- `cbm_k_setnam.s` seem to use rc2 and rc3(?)

**Comment by cnelson20** [comment]
Thanks for the ping, I'll try to take a look at this.

**Comment by cnelson20** [comment]
I haven't found the root cause of the issue since it seems all the registers are set correctly but when using OPEN on a file the secondary address must be between 2 and 14.

**Comment by cnelson20** [comment]
There was a bug in the implementation of cbm_k_open() and some in your code.

Secondary address for OPEN'ed files on cbm systems must be between 2 and 14. The meaning of the secondary is different that when you are LOAD'ing a file. It's usually easiest to set the LFN to the same value, but it can be any number < 128 I believe.
Before returning to the user, it's nice to CLALL so that the basic prompt is reading from the user again.

The problem in my OPEN implementation is that it should have discarded the value in .A if .C (the carry flag) is clear (=0), which it previously didn't. A PR is being made right after I write this.

I tested using the Box16 Commander X16 Emulator, but the details on files should hold on the C64. This edit to your code snippet worked for me and printed 0.
```c
// cl65 cbm_open.c -o open-cc65.prg --target c64
// mos-c64-clang cbm_open.c -o open-clang.prg
#include <cbm.h>
#include <stdio.h>

const char* filename = "SOMEFILE";

int main() {
    unsigned char s1, s2;
    unsigned char lfn = 11;
    unsigned char device = 8;
    unsigned char secondary_addr = 11;

    cbm_k_setlfs(lfn, device, secondary_addr);
    cbm_k_setnam(filename);

    s1 = cbm_k_open(); // Expected = 0; Clang = 199
    s2 = cbm_k_chkin(lfn); // Expected = 0; on clang this causes the screen to scroll
    cbm_k_clall();
    printf("OPEN STATUS = %d\n", s1);
    return 0;
}
```

**Comment by mysterymath** [comment]
@mlund, when you get the chance, can you confirm whether PR #103 and the above comments resolve this issue?

**Comment by mlund** [comment]
Thanks a lot for looking into this! This fixed it on CX16, so I think we can safely assume it's OK on the C64 (due to ROM overlap).
